version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run: git clone https://github.com/aliartiza75/python-list-comparison.git 
      - run: ls
      - run: pwd
